import test from 'node:test';
import assert from 'node:assert/strict';
import {handleEngineering} from '../server/engineering-worker.mjs';
const input={modelId:'sahara-s9',cropId:'corn',volume:1000,initialMoisture:25,finalMoisture:15,fuelId:'diesel',fuelPrice:60,electricityPrice:8,serviceEnabled:false,serviceVolume:0,serviceTariff:null,elevatorTariff:200,elevatorBasis:'tonne',elevatorOtherPerTonne:0,ownOtherPerTonne:0,delayedSale:false,currentGrainPrice:null,futureGrainPrice:null,dryerPrice:100000,installation:10000,additionalInvestment:0,availableHours:null};
function setup(){const store=new Map();const env={ALLOWED_ORIGINS:'https://example.test',RETENTION_DAYS:'30',RATE_LIMITER:{limit:async()=>({success:true})},CRM_WEBHOOK_URL:'https://crm.test',CALCULATIONS:{get:async k=>store.get(k),put:async(k,v)=>store.set(k,v)}};let deliveries=0;const fetcher=async()=>{deliveries++;return new Response('{}');};const call=(path,body,token='',origin='https://example.test')=>handleEngineering(new Request('https://worker.test/api/'+path,{method:'POST',headers:{Origin:origin,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(body)}),env,fetcher);return {store,env,call,deliveries:()=>deliveries};}
const contact={name:'Test User',phone:'+380991234567',email:'',preferredChannel:'phone'};
await test('API calculates server-side and keeps private token out of results',async()=>{const s=setup(),r=await s.call('calculations',{input,locale:'uk',result:{paybackSeasons:1}});assert.equal(r.status,201);const b=await r.json();assert.equal(b.result.paybackSeasons,null);assert.equal(b.result.capacity,6);const stored=JSON.parse(s.store.get(b.calculationId));assert.notEqual(stored.tokenHash,b.accessToken);assert.equal(stored.result.engineVersion,'2.0.0');});
await test('API rejects foreign origins, invalid input and absent retention',async()=>{const s=setup();assert.equal((await s.call('calculations',{input,locale:'uk'},'','https://evil.test')).status,403);assert.equal((await s.call('calculations',{input:{...input,volume:-1},locale:'uk'})).status,422);s.env.RETENTION_DAYS='';assert.equal((await s.call('calculations',{input,locale:'uk'})).status,503);});
await test('Report requires calculation token and saved contact',async()=>{const s=setup(),b=await(await s.call('calculations',{input,locale:'uk'})).json();assert.equal((await s.call('calculations/report',{calculationId:b.calculationId},'wrong')).status,403);assert.equal((await s.call('calculations/report',{calculationId:b.calculationId},b.accessToken)).status,403);});
await test('Selected channel, explicit consent and repeated lead delivery',async()=>{const s=setup(),b=await(await s.call('calculations',{input,locale:'en'})).json();const body={calculationId:b.calculationId,contact,reportConsent:true,marketingConsent:false};assert.equal((await s.call('leads',{...body,reportConsent:false},b.accessToken)).status,400);assert.equal((await s.call('leads',{...body,contact:{...contact,phone:''}},b.accessToken)).status,400);const response=await s.call('leads',body,b.accessToken);assert.equal(response.status,200);assert.equal((await response.json()).crmDelivered,true);await s.call('leads',body,b.accessToken);assert.equal(s.deliveries(),1);const record=JSON.parse(s.store.get(b.calculationId));assert.equal(record.lead.marketingConsent,false);assert.equal(record.input.volume,1000);});
await test('Unavailable CRM delivery is reported accurately while lead stays saved',async()=>{const s=setup(),b=await(await s.call('calculations',{input,locale:'uk'})).json();const r=await handleEngineering(new Request('https://worker.test/api/leads',{method:'POST',headers:{Origin:'https://example.test',Authorization:'Bearer '+b.accessToken},body:JSON.stringify({calculationId:b.calculationId,contact,reportConsent:true,marketingConsent:false})}),s.env,async()=>new Response('',{status:503}));const result=await r.json();assert.equal(result.accepted,true);assert.equal(result.crmDelivered,false);assert.ok(JSON.parse(s.store.get(b.calculationId)).lead);});
